apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: etos-suite-starter
    literals:
      - SUITE_RUNNER=registry.nordix.org/eiffel/etos-suite-runner:899019c0
      - LOG_LISTENER=registry.nordix.org/eiffel/etos-log-listener:899019c0
