apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
configMapGenerator:
  - name: etos-suite-starter
    literals:
      - SUITE_RUNNER=registry.nordix.org/eiffel/etos-suite-runner:36477b21
      - LOG_LISTENER=registry.nordix.org/eiffel/etos-log-listener:36477b21
patches:
  - target:
      name: etos-suite-runner
      kind: ConfigMap
    patch: |-
      - op: add
        path: /data/ETR_VERSION
        value: 3.5.0
