apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
configMapGenerator:
  - name: etos-suite-starter
    literals:
      - SUITE_RUNNER=ghcr.io/eiffel-community/etos-suite-runner:1ce14c07
      - LOG_LISTENER=ghcr.io/eiffel-community/etos-log-listener:1ce14c07
patches:
  - target:
      name: etos-suite-runner
      kind: ConfigMap
    patch: |-
      - op: add
        path: /data/ETR_VERSION
        value: 3.6.0
